# Generated by Django 5.1.1 on 2024-09-18 09:42

import django.db.models.deletion
import trainers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_certificato', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Certificati',
            },
        ),
        migrations.CreateModel(
            name='PersonalTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_di_nascita', models.DateField()),
                ('bio', models.TextField(max_length=500)),
                ('preferenze', models.CharField(choices=[('BB', 'BodyBuilding'), ('PL', 'PowerLifting'), ('CL', 'Calisthenics'), ('ST', 'StrongMen'), ('YG', 'Yoga'), ('PS', 'Pilates'), ('AR', 'Aerobico')], max_length=2)),
                ('immagine_profilo', models.ImageField(blank=True, null=True, upload_to=trainers.models.foto_profilo_upload_path)),
                ('certificati', models.ManyToManyField(blank=True, related_name='personal_trainers', to='trainers.certificato')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Trainer',
                'verbose_name_plural': 'Personal Trainers',
            },
        ),
        migrations.AddField(
            model_name='certificato',
            name='personal_trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificati_caricati', to='trainers.personaltrainer'),
        ),
    ]
