# Generated by Django 5.1.1 on 2024-09-18 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaltrainer',
            name='certificati',
        ),
        migrations.AddField(
            model_name='personaltrainer',
            name='certificati',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_trainer_certificato', to='trainers.certificato'),
        ),
    ]
