# Generated by Django 5.1.1 on 2024-09-18 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_remove_personaltrainer_certificati_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificato',
            name='personal_trainer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificati_caricati', to='trainers.personaltrainer'),
        ),
    ]
