# Generated by Django 5.1.1 on 2024-09-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField()),
                ('bio', models.TextField(max_length=500)),
                ('preferenze', models.CharField(choices=[('BB', 'BodyBuilding'), ('PL', 'PowerLifting'), ('CL', 'Calisthenics'), ('ST', 'StrongMen'), ('YG', 'Yoga'), ('PS', 'Pilates'), ('AR', 'Aerobico')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Utenti',
            },
        ),
    ]
