# Generated by Django 5.1.1 on 2024-09-16 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegitratoUtente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField()),
                ('bio', models.TextField(max_length=500)),
                ('preferenze', models.CharField(choices=[('BB', 'BodyBuilding'), ('PL', 'PowerLifting'), ('CL', 'Calisthenics'), ('ST', 'StrongMen'), ('YG', 'Yoga'), ('PS', 'Pilates'), ('AR', 'Aerobico')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UtentiRegistrati',
            },
        ),
    ]
