# Generated by Django 5.1.1 on 2024-09-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_regitratoutente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utente',
        ),
    ]
