# Generated by Django 5.1.1 on 2024-09-17 14:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_utente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegitratoUtente',
            new_name='RegistratoUtente',
        ),
    ]
