# Generated by Django 5.1.1 on 2024-09-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_regitratoutente_registratoutente'),
        ('reviews', '0001_initial'),
        ('trainers', '0004_remove_personaltrainer_certificati_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recensione',
            unique_together={('registrato_utente', 'personal_trainer')},
        ),
    ]
