# Generated by Django 5.1.1 on 2024-10-01 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_rename_regitratoutente_registratoutente'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichiestaPersonalTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=500)),
                ('competenze', models.TextField(blank=True, max_length=500)),
                ('data_richiesta', models.DateTimeField(auto_now_add=True)),
                ('approvato', models.BooleanField(default=False)),
                ('registrato_utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.registratoutente')),
            ],
        ),
    ]
