# Generated by Django 5.1.1 on 2024-10-01 15:52

import django.db.models.deletion
import gestione.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='richiestapersonaltrainer',
            options={'verbose_name_plural': 'Richieste di Personal Trainer'},
        ),
        migrations.RemoveField(
            model_name='richiestapersonaltrainer',
            name='registrato_utente',
        ),
        migrations.AddField(
            model_name='richiestapersonaltrainer',
            name='cognome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='richiestapersonaltrainer',
            name='data_di_nascita',
            field=models.DateField(default='1900-1-1'),
        ),
        migrations.AddField(
            model_name='richiestapersonaltrainer',
            name='immagine_profilo',
            field=models.ImageField(blank=True, null=True, upload_to=gestione.models.foto_profilo_upload_path),
        ),
        migrations.AddField(
            model_name='richiestapersonaltrainer',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='richiestapersonaltrainer',
            name='preferenze',
            field=models.CharField(choices=[('BB', 'BodyBuilding'), ('PL', 'PowerLifting'), ('CL', 'Calisthenics'), ('ST', 'StrongMen'), ('YG', 'Yoga'), ('PS', 'Pilates'), ('AR', 'Aerobico')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='richiestapersonaltrainer',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='richiestapersonaltrainer',
            name='bio',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='richiestapersonaltrainer',
            name='competenze',
            field=models.TextField(default='Nessuna competenza', max_length=500),
        ),
    ]
