# Generated by Django 5.1.1 on 2024-10-01 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0003_alter_richiestapersonaltrainer_cognome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='richiestapersonaltrainer',
            name='preferenze',
            field=models.CharField(choices=[('BB', 'BodyBuilding'), ('PL', 'PowerLifting'), ('CL', 'Calisthenics'), ('ST', 'StrongMen'), ('YG', 'Yoga'), ('PS', 'Pilates'), ('AR', 'Aerobico')], max_length=2),
        ),
        migrations.AlterField(
            model_name='richiestapersonaltrainer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
