# Generated by Django 5.1.1 on 2024-09-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prenotazione',
            options={'verbose_name_plural': 'Prenotazioni'},
        ),
        migrations.AlterUniqueTogether(
            name='prenotazione',
            unique_together=set(),
        ),
    ]
