# Generated by Django 5.1.1 on 2024-10-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_prenotazione_options_and_more'),
        ('trainers', '0004_remove_personaltrainer_certificati_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prenotazione',
            unique_together={('personal_trainer', 'fascia_oraria', 'data_prenotazione')},
        ),
    ]
